version: '3'
services:

#  web:
#    container_name: web
#    build: './web'
#    ports:
#      - "8080:3000"
#    depends_on:
#      - usuarios
#      - autoescuelas
#      - alumnos
#    environment:
#      - API_URL = http://localhost:3000/api/v1

#  web:
#    container_name: web
#    restart: always
#    build: './web'
#    command: npm run dev
#    ports:
#      - "3000:3000"
#    volumes:
#      - /home/alejandro/Documentos/dockerVolumes/eliminar/:/app/dist
#    depends_on:
#      - autoescuelas
#      - alumnos

  usuarios:
#    container_name: ms-usuarios
    restart: always
    build: './api/usuarios'
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_DB_URI= mongodb://mongo:27017/openvial

#  autoescuelas:
#    container_name: ms-autoescuelas
#    restart: always
#    build: './api/autoescuelas'
#    ports:
#      - "3002:3000"
#    depends_on:
#      - mongo
#    environment:
#      - MONGO_DB_URI= mongodb://mongo:27017/openvial

#  alumnos:
#    container_name: ms-alumnos
#    restart: always
#    build: './api/alumnos'
#    ports:
#      - "3003:3000"
#    depends_on:
#      - mongo
#    environment:
#      - MONGO_DB_URI= mongodb://mongo:27017/openvial

  mongo:
#    container_name: mongo
    image: mongo:3.7
    command: mongod --smallfiles
    volumes:
      - /home/alejandro/Documentos/dockerVolumes/databases/mongo/v3.7:/data/db
    ports:
      - "27017:27017"
      
#  nginx:
#    container_name: nginx
#    image: nginx:1.15
#    ports:
#      - "8080:8080"
#    depends_on:
#      - web
#      - usuarios
#      - autoescuelas
#      - alumnos
#    volumes:
#      - ./web/dist:/srv/www/static
#      - ./default.conf:/etc/nginx/conf.d/default.conf
